### Find Note
GET http://localhost:3000/api/notes

### Search Note
GET http://localhost:3000/api/notes?search=active&is_active=false

### Find One Note
GET http://localhost:3000/api/notes/62994b4e8e2fec01a648cb09

### Create Note
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "name": "No active Test",
  "description": "No active Description",
  "user": "carloscdev",
  "status": "DONE",
  "is_active": false
}

### Delete Note
DELETE http://localhost:3000/api/notes/6299450b559fe84f3b92c1b9

### Update Note
PUT http://localhost:3000/api/notes/62994000b081fed496248c29
Content-Type: application/json

{
  "name": "Update Third Test",
  "description": "Five Description",
  "user": "carloscdev"
}
