### Find Note
GET http://localhost:3000/api/notes

### Search Note
GET http://localhost:3000/api/notes?search=active&is_active=false

### Find One Note
GET http://localhost:3000/api/notes/62995393d8665f477f8e4263

### Create Note
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "name": "No active Test",
  "description": "No active Description",
  "user": "carloscdev",
  "status": "DONE",
  "is_active": false
}

### Delete Note
DELETE http://localhost:3000/api/notes/62995393d8665f477f8e4263

### Update Note
PUT http://localhost:3000/api/notes/6299535dd8665f477f8e425d
Content-Type: application/json

{
  "name": "Updateeeee",
  "description": "Five Description",
  "user": "carloscdev",
  "status": "IN_PROCESS",
  "is_active": false
}
